#!/bin/bash

if [ $# -lt 1 ];then
        echo "Usage : $0 <fileinput> <fileoutput>" && exit
fi

openssl=$(which openssl)

if ${openssl} enc -aes-256-cfb8 -a -salt -pbkdf2 -in ${1} -out ${2}; then
        echo "Successfully converted"
else
        echo "Failed Conversion"
fi
