#!/usr/bin/env python3
import subprocess
import json

cmd = '/usr/local/bin/pip3 list --user --format json --no-index'
output = subprocess.check_output(cmd, shell=True)

data = json.loads(output)
for obj in data:
  print('\''+ obj['name'] + '\'' + ': ' + '\'' + obj['version'] + '\'')
