#!/usr/bin/env python3
import sys, getopt
import subprocess
import json

def main(argv):
  req_file = ''
  try:
    opts, args = getopt.getopt(argv, 'hf:', ['rfile='])
  except getopt.GetoptError:
    print("reqpydiff -f <location of requirements.txt>")
    sys.exit(2)
  for opt, arg in opts:
    if opt == '-h':
      print("reqpydiff -f <location of requirements.txt>")
      sys.exit()
    elif opt in ('-f', '--rfile'):
      req_file = arg

  cmd = '/usr/local/bin/pip3 list --user --format json --no-index'
  output = subprocess.check_output(cmd, shell=True)
  pyreq = []
  pylocal = []
  data = json.loads(output)
  for obj in data:
    pylocal.append(obj['name'])

  with open(req_file, 'rb') as fin:
    content = fin.readlines()
    fin.close()

  for line in content:
    temp = line.decode("utf-8").rstrip().lstrip().split('==')
    pyreq.append(temp[0])
  print('Missing modules: '+str(set(pyreq).difference(pylocal)))

if __name__ == "__main__":
   main(sys.argv[1:])
