#!/usr/bin/env python3
# License: MIT
# Author: k2patel <k2patel@live.com>
import sys, getopt
import subprocess
import json

def main(argv):
  # Initialize and handle options
  req_file = ''
  try:
    opts, args = getopt.getopt(argv, 'hf:', ['rfile='])
  except getopt.GetoptError:
    print("localpypi -f <location of requirements.txt>")
    sys.exit(2)
  for opt, arg in opts:
    if opt == '-h':
      print("localpypi -f <location of requirements.txt>")
      sys.exit()
    elif opt in ('-f', '--rfile'):
      req_file = arg
      
  # Create array of local modules
  cmd = '/usr/local/bin/pip3 list --user --format json --no-index'
  output = subprocess.check_output(cmd, shell=True)

  pylocal = []
  data = json.loads(output)
  for obj in data:
    pylocal.append(obj['name'])

  # Read requirements.txt file and compare if modulee exists in local
  with open(req_file, 'rb') as fin:
    content = fin.readlines()
    fin.close()

  for line in content:
    temp = line.decode("utf-8").rstrip().lstrip().split('==')
    if temp[0] not in pylocal:
      print(line.decode("utf-8").rstrip().lstrip().replace('==', ': '))

if __name__ == "__main__":
   main(sys.argv[1:])
