#!/usr/bin/env python3
fname = 'requirements.txt'
with open(fname, 'r', encoding='utf-8') as fhd:
    print("Following modules require to be installed:")
    for line in fhd:
        try:
            exec("import " + line)
        except:
            if line.find('==') == -1 :
                print(line.rstrip('\r\n') + ': latest')
            else:
                print(line.replace('==', ': '), end='')
