#!/usr/bin/env bash
#
#############
#
# Renew Certificate using lets-encrypt
# Author : Ketan Patel <k2patel.in>
# License : BSD
#
#############
source /etc/bashrc

# Globals ( Please update )
#
ldomains=('rpm.k2patel.in' 'ip.k2patel.in' 'wiki.k2patel.in')
LETSENCRYPT_HOME="/root/letsencrypt"
WEBSERVER="nginx"

# Enable System level logging
# Redirect log to logger
exec 1> >(logger -t $(basename $0)) 2>&1

for i in ${ldomains[@]}
  do
    ${LETSENCRYPT_HOME}/certbot-auto certonly -c /etc/letsencrypt/config/${i}.conf --renew-by-default
  done

# Start web services
if /usr/bin/systemctl restart ${WEBSERVER} ; then
   echo "Web service re-started after certificate renewal."
else
   echo "Failed to start web services"
fi
