#! /usr/bin/env python

import sys
import requests
import argparse
from requests.auth import HTTPBasicAuth
import base64
import ConfigParser

#Parse arguments
parser = argparse.ArgumentParser(
    description=__doc__)

parser.add_argument("-a", "--action", help="Action to take 'reload', 'stop', 'start'", type=str, default=reload)
parser.add_argument("-c", "--context", help="Enter name of webapp, where you want to send action", type=str, required=True )

args = parser.parse_args()

config = ConfigParser.ConfigParser()
config.readfp(open(r'tomcat_wrapper.conf'))

username = config.get('access', 'username')
password = base64.b64decode(config.get('access', 'password'))
_host = config.get('access', 'host')
_port = config.get('access', 'port')
_manager = config.get('access', 'manager')

URL = 'http://' + _host + ':' + _port + _manager + '/text/' + args.action + '?path=/' + args.context

resp = requests.get(URL, auth=HTTPBasicAuth(username, password))

if 'OK' not in resp.text:
	print "Failed with following error : \n" + resp.text
	sys.exit(1)
else:
    print "Successfull : \n" + resp.text
    sys.exit(0)
